ALTER TABLE "Series"
ADD COLUMN "weekday" TEXT NOT NULL DEFAULT 'mon',
ADD COLUMN "freeVolumeCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "previewEpisodeCount" INTEGER NOT NULL DEFAULT 3;

ALTER TABLE "Order"
ADD COLUMN "volumeNumber" INTEGER NOT NULL DEFAULT 1;
